### ISSUE TITLE
Exception during import without Match[@PreRetrieveAll] attribute

### ISSUE THREAD

**Issue by majakubowski** [Innofactor/Innofactor.Crm.CI#11]
During import, when there is no Match node in Import node, exception is thrown:

```
Nullable object must have a value.

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.get_Value()
   at Cinteros.Crm.Utils.Shuffle.Shuffler.ImportDataBlock(DataBlock block, CintDynEntityCollection cEntities)
   at Cinteros.Crm.Utils.Shuffle.Shuffler.ImportToCRM(ShuffleBlocks blocks)
   at Cinteros.Crm.Utils.Shuffle.Shuffler.QuickImport(IContainable container, XmlDocument Definition, XmlDocument Data, EventHandler`1 ShuffleEventHandler, String defpath, Boolean clearRemainingShuffleVars)
   at Cinteros.Crm.Utils.Shuffle.Shuffler.QuickImport(IContainable container, XmlDocument Definition, XmlDocument Data, EventHandler`1 ShuffleEventHandler, String defpath)
   at Innofactor.Crm.Shuffle.Runner.ShuffleRunner.<>c__DisplayClass10_0.<btnShuffle_Click>b__0(DoWorkEventArgs eventargs)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by shytikov** [comment]
@imranakram  will be looking on that!

**Comment by majakubowski** [comment]
@shytikov @imranakram 
hi, I already fixed bug and pulled request with my changes.
ps. you made a great tool ;)

**Comment by shytikov** [comment]
@majakubowski  thanks, but it's mostly @rappen  work! He is MVP ⭐️ :)
